### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by angarsa15** [RXTX4816/OBD-KKL-KW1281-ARDUINO-TRIPCOMPUTER#1]
Hi Mate!

Your project seems amazing, I am trying to make the same, but the codes that I used didn't work to me (I've got a MK IV Golf with TDI AHF Engine), could you please upload the code to github? I am searching for it on the zip file but I didn't found it

Thanks for your project!

Regards, Toni

**Comment by RXTX4816** [comment]
Hello!

In that case you probably have the 038 906 018 j BOSCH ECU. The code can be found in src/obdisplay.cpp. That is the only code file.

Take care.

**Comment by angarsa15** [comment]
Thank you very much!  I'm a little new with arduino and I was looking for
.ino file

Now connects to the ECU and I will try to adapt your code to put an
external button to change the pages of the lcd info!

Regards, Toni

**Comment by RXTX4816** [comment]
No problem. Good luck.
